name: install

inputs:
  python-version:
    description: Python version
    required: false
    default: '3.11'
    type: string

outputs:
  key:
    description: Cache key that identifies the installation
    value: ${{ steps.cache-key.outputs.key }}

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      id: setup-python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
      with:
        python-version: ${{ inputs.python-version }}

    - name: Get cache key
      id: cache-key
      shell: bash
      run: |
        if [ "${RUNNER_OS}" = 'macOS' ]; then
          readonly name="$(sw_vers -productName)"
          readonly version="$(sw_vers -productVersion)"
        elif [ "${RUNNER_OS}" = 'Linux' ]; then
          readonly name="$(lsb_release -i -s)"
          readonly version="$(lsb_release -r -s)"
        else
          exit 1
        fi
        echo "key=${name}-${version}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}" >> $GITHUB_OUTPUT

    - name: Restore installation
      id: restore
      uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57
      with:
        path: |
          meltingpot/assets
          venv
        key: install-${{ steps.cache-key.outputs.key }}

    - name: Create venv
      if: steps.restore.outputs.cache-hit != 'true'
      shell: bash
      run: |
        python -m venv venv

    - name: Activate venv
      shell: bash
      run: |
        echo "${PWD}/venv/bin" >> $GITHUB_PATH

    - name: Install
      if: steps.restore.outputs.cache-hit != 'true'
      shell: bash
      run: |
        pip install --require-virtualenv --require-hashes -r requirements.txt
        pip install --require-virtualenv --no-deps --no-index --no-build-isolation --editable .

    - name: Show installation
      shell: bash
      run: |
        which python
        python --version
        which pip
        pip --version
        which pylint
        pylint --version
        which pytest
        pytest --version
        which pytype
        pytype --version
        pip list

    - name: Save installation
      if: steps.restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57
      with:
        path:  |
          meltingpot/assets
          venv
        key: ${{ steps.restore.outputs.cache-primary-key }}
