name: pylint-examples

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/install-examples/action.yml'
      - '.github/actions/install-meltingpot/action.yml'
      - '.github/workflows/pylint-examples.yml'
      - '.pylintrc'
      - 'examples/**'
      - 'meltingpot/**'
      - 'setup.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/install-examples/action.yml'
      - '.github/actions/install-meltingpot/action.yml'
      - '.github/workflows/pylint-examples.yml'
      - '.pylintrc'
      - 'examples/**'
      - 'meltingpot/**'
      - 'setup.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  pylint:
    name: Lint examples
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Melting Pot
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Install examples
        uses: ./.github/actions/install-examples

      - name: Run PyLint on examples
        run: pylint --errors-only examples
