name: pytype-meltingpot

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/install-meltingpot/action.yml'
      - '.github/workflows/pytype-meltingpot.yml'
      - 'examples/**'
      - 'meltingpot/**'
      - 'pyproject.toml'
      - 'setup.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/install-meltingpot/action.yml'
      - '.github/workflows/pytype-meltingpot.yml'
      - 'examples/**'
      - 'meltingpot/**'
      - 'pyproject.toml'
      - 'setup.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  pytype:
    name: Typecheck Melting Pot
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Melting Pot
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Install Melting Pot
        uses: ./.github/actions/install-meltingpot

      - name: Run PyType on Melting Pot
        run: pytype meltingpot
