# A workflow to test the sdist that will be released to PyPI

name: sdist-test

on:
  workflow_dispatch:

permissions: read-all

jobs:
  sdist-test:
    name: Test sdist
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout Melting Pot
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Build source distribution
        run: python setup.py sdist

      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install pytest-xdist setuptools

      - name: Install source distribution
        run: |
          pip install dist/*.tar.gz

      - name: Test source distribution
        run: |
          pytest -n auto --pyargs meltingpot
